### ISSUE TITLE
renaming project fails - 'cannot find module "fs-extra" '

### ISSUE THREAD

**Issue by NikoMontana** [invertase/react-native-firebase-starter#16]
**Nikolas-MBP:03-StartupAPP dev$ npm run rename**

RNFirebaseStarter@0.1.0 rename /Users/dev/Desktop/workspace/ReactNative/03-StartupAPP
node ./bin/rename.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dev/Desktop/workspace/ReactNative/03-StartupAPP/bin/rename.js:1:74)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! RNFirebaseStarter@0.1.0 rename: `node ./bin/rename.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the RNFirebaseStarter@0.1.0 rename script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dev/.npm/_logs/2018-02-25T11_41_41_531Z-debug.log

**Comment by NikoMontana** [comment]
Forgot to npm install bevore...
