### ISSUE TITLE
new project, npm start leads to Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by spacewaffle** [invertase/react-native-firebase-starter#48]
After following the starter instructions up to the npm start command, I ran into this issue:
node v10.8.0
npm  v6.2.0
OSX  v10.13.6

```
npm start

 rntest@0.1.0 start /Users/spacewaffle/sites/react-native-firebase-starter
 react-native start

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/spacewaffle/sites/react-native-firebase-starter/node_modules/metro/src/babel-bridge.js:40:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/spacewaffle/sites/react-native-firebase-starter/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rntest@0.1.0 start: `react-native start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rntest@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/spacewaffle/.npm/_logs/2018-08-05T08_26_32_122Z-debug.log

```

**Comment by spacewaffle** [comment]
Should I just downgrade to RN 0.55 to get going now then or is there a different/better way to go about things?

**Comment by Salakar** [comment]
@spacewaffle stick with 0.55 for now yes.

**Comment by spacewaffle** [comment]
Hey @Salakar, I'm still having the same issue even with the downgrade to 0.55.3. Is there anything else I have to do on top of the setup instructions in the readme to install with the older version? All I did was lock react-native to 0.55.3 in package.json.
