### ISSUE TITLE
Could not parse the simulator list output

### ISSUE THREAD

**Issue by samcorcos** [invertase/react-native-firebase-starter#76]
Running OSX 10.13.6

I went through the instructions and configured the app.

`npm start` appears to work.

When I run `npm run ios` I get the following error:

```
Found Xcode workspace MyApp.xcworkspace
2018-11-06 11:01:38.697 simctl[12759:1609856] CoreSimulator detected relocation or version change.  Framework path (/Library/Developer/PrivateFrameworks/CoreSimulator.framework) and version (581.2) does not match existing job path (/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc) and version (572.2).  Attempting to remove the stale service in order to add the expected version.

Could not parse the simulator list output

Error: Could not parse the simulator list output
    at resolve (/Users/xxxx/code/MyApp/node_modules/react-native/local-cli/runIOS/runIOS.js:144:13)
    at new Promise (<anonymous>)
    at runOnSimulator (/Users/xxxx/code/MyApp/node_modules/react-native/local-cli/runIOS/runIOS.js:134:10)
    at Object.runIOS [as func] (/Users/xxxx/code/MyApp/node_modules/react-native/local-cli/runIOS/runIOS.js:106:12)
    at Promise.resolve.then (/Users/xxxx/code/MyApp/node_modules/react-native/local-cli/cliEntry.js:117:22)
```

**Comment by samcorcos** [comment]
I ran `brew upgrade` to update iOS Simulator/Xcode and it appears to have solved the problem, in case anyone else runs into this issue.
