### ISSUE TITLE
Rename script does not work

### ISSUE THREAD

**Issue by brunoald** [invertase/react-native-firebase-starter#8]
Hello! I'm running the steps to install the app but I'm seeing this when I try to run the command `npm run rename`:

```
➜  react-native-firebase-starter git:(master) ✗ npm run rename

> RNFirebaseStarter@0.1.0 rename /Users/bdias/Code/react-native-firebase-starter
> node ./bin/rename.js

/Users/bdias/Code/react-native-firebase-starter/bin/rename.js:121
const run = async () => {
                  ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! RNFirebaseStarter@0.1.0 rename: `node ./bin/rename.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the RNFirebaseStarter@0.1.0 rename script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bdias/.npm/_logs/2017-11-25T11_56_38_870Z-debug.log
```

My version of node is `v6.9.1` and npm version is `5.5.1`. My operating system is macOS High Sierra 10.13.

Any ideas on why this could be happening?

**Comment by Ehesp** [comment]
Asyc is supported in Node 7.6+ I believe - I suggest upgrading to Node 8 which is now in LTS.

**Comment by chrisbianca** [comment]
Thanks for flagging - I've added a note to the instructions mentioning the minimum node version
